name: CICD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Convert
        id: convert
        uses: ./
        with:
          text: |
            # Heading 1

            ## Heading 2

            [Link](http://example.com)

            * List Item 1
            * List Item 2

      - name: Verify
        shell: bash
        env:
          ACTUAL: ${{ steps.convert.outputs.text }}
          EXPECTED: |
            *Heading 1*

            *Heading 2*

            <http://example.com|Link>

            •   List Item 1
            •   List Item 2
        run: |
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "Actual: '$ACTUAL'"
            echo "Expected: '$EXPECTED'"
            exit 1
          fi
