name: CICD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Convert
        id: convert
        uses: ./
        with:
          text: |
            # Heading 1

            ## Heading 2

            [Link](http://example.com)

            * List Item 1
            * List Item 2

      - name: Verify
        shell: bash
        env:
          ACTUAL: ${{ steps.convert.outputs.text }}
          EXPECTED: |
            *Heading 1*

            *Heading 2*

            <http://example.com|Link>

            •   List Item 1
            •   List Item 2
        run: |
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "Actual: '$ACTUAL'"
            echo "Expected: '$EXPECTED'"
            exit 1
          fi
